AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    LogInsights

    Building Simple Log Analysis and Search Tool with ES and Lambda Functions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3
        MemorySize: 128

        Tracing: Active
    Api:
        TracingEnabled: true
Resources:
    LogInsightsFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: core/
            Handler: app.lambda_handler
            Runtime: python3.8
            Architectures:
                - x86_64
            Events:
                SetLogsToES:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: post
                GetLogsFromES:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: get

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    LogInsightsApi:
        Description: API Gateway endpoint URL for Prod stage for Hello World function
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
    LogInsightsFunction:
        Description: Hello World Lambda Function ARN
        Value: !GetAtt LogInsightsFunction.Arn
    LogInsightsFunctionIamRole:
        Description: Implicit IAM Role created for Hello World function
        Value: !GetAtt LogInsightsFunctionRole.Arn
